//For higher compiling speed

//client
#include "aux-skills.cpp"
#include "client.cpp"
#include "clientplayer.cpp"
#include "clientstruct.cpp"

//core
#include "audio.cpp"
#include "banpair.cpp"
#include "card.cpp"
#include "engine.cpp"
#include "general.cpp"
#include "jsonutils.cpp"
#include "lua-wrapper.cpp"
#include "player.cpp"
#include "protocol.cpp"
#include "record-analysis.cpp"
#include "RoomState.cpp"
#include "settings.cpp"
#include "skill.cpp"
#include "structs.cpp"
#include "util.cpp"
#include "WrappedCard.cpp"

//dialog
#include "AboutUs.cpp"
#include "cardeditor.cpp"
#include "cardoverview.cpp"
#include "choosegeneraldialog.cpp"
#include "configdialog.cpp"
#include "connectiondialog.cpp"
#include "customassigndialog.cpp"
#include "distanceviewdialog.cpp"
#include "generaloverview.cpp"
#include "mainwindow.cpp"
#include "packagingeditor.cpp"
#include "playercarddialog.cpp"
#include "roleassigndialog.cpp"
#include "scenario-overview.cpp"

//package
#include "bgm-package.cpp"
#include "exppattern.cpp"
#include "firepackage.cpp"
#include "formation.cpp"
#include "god.cpp"
#include "hegemony.cpp"
#include "joypackage.cpp"
#include "lingpackage.cpp"
#include "maneuvering.cpp"
#include "mountainpackage.cpp"
#include "nostalgia.cpp"
#include "package.cpp"
#include "power.cpp"
#include "sp-package.cpp"
#include "special1v1-package.cpp"
#include "special3v3-package.cpp"
#include "standard-cards.cpp"
#include "standard-generals.cpp"
#include "standard-skillcards.cpp"
#include "standard.cpp"
#include "thicket.cpp"
#include "tigerfly.cpp"
#include "wind.cpp"
#include "wisdompackage.cpp"
#include "yitianpackage.cpp"
#include "yjcm-package.cpp"
#include "yjcm2012-package.cpp"
#include "yjcm2013-package.cpp"

//scenario
#include "boss-mode-scenario.cpp"
#include "couple-scenario.cpp"
#include "fancheng-scenario.cpp"
#include "guandu-scenario.cpp"
#include "miniscenarios.cpp"
#include "scenario.cpp"
#include "scenerule.cpp"
#include "zombie-scenario.cpp"

//server
#include "ai.cpp"
#include "contestdb.cpp"
#include "gamerule.cpp"
#include "generalselector.cpp"
#include "main.cpp"
#include "room.cpp"
#include "roomthread.cpp"
#include "roomthread1v1.cpp"
#include "roomthread3v3.cpp"
#include "roomthreadxmode.cpp"
#include "server.cpp"
#include "serverplayer.cpp"

//ui
#include "button.cpp"
#include "cardcontainer.cpp"
#include "carditem.cpp"
#include "chatwidget.cpp"
#include "clientlogbox.cpp"
#include "dashboard.cpp"
#include "GenericCardContainerUI.cpp"
#include "indicatoritem.cpp"
#include "magatamasItem.cpp"
#include "photo.cpp"
#include "pixmapanimation.cpp"
#include "qsanbutton.cpp"
#include "QSanSelectableItem.cpp"
#include "rolecombobox.cpp"
#include "roomscene.cpp"
#include "SkinBank.cpp"
#include "sprite.cpp"
#include "startscene.cpp"
#include "TablePile.cpp"
#include "TimedProgressBar.cpp"
#include "uiUtils.cpp"
#include "window.cpp"

//util
#include "detector.cpp"
#include "nativesocket.cpp"
#include "recorder.cpp"

//END